### ISSUE TITLE
Use Emscripten's ZLIB

### ISSUE THREAD

**Issue by mmontag** [wothke/webn64#1]
I notice you are compiling with zlib source - but for convenience you can instead build with the linker flag `-s USE_ZLIB=1`.

Emscripten has it built in since version 1.26.1.

**Comment by wothke** [comment]
thanks, I had overlooked that feature. I'll try it next time I touch the project.

**Comment by wothke** [comment]
just tried it on my vgmplay based backend and for some reason it results in a 15kb larger lib. so I guess it isn't worth the effort to remove something that I already have.
